-- Campos autoincremento: É um tipo aplicado em uma coluna normalmente usado para chaves primárias que a cada nova inserção no banco esse campo se autocompleta.
CREATE table exemplo (
	idexemplo serial not null, -- Campo 'serial' irá permitir que o próprio postgre atualize os ID da chave primária automaticamente.
	nome varchar(50) not null,

	constraint pk_exemplo_idexemplo primary key (idexemplo)
);

-- Inserindo dados a tabela exemplo sem a necessidade de colocar o idexemplo pois ele já autoincrementa
INSERT INTO EXEMPLO (NOME) VALUES ('Exemplo 1');
INSERT INTO EXEMPLO (NOME) VALUES ('Exemplo 2');
INSERT INTO EXEMPLO (NOME) VALUES ('Exemplo 3');
INSERT INTO EXEMPLO (NOME) VALUES ('Exemplo 4');
INSERT INTO EXEMPLO (NOME) VALUES ('Exemplo 5');

select * from exemplo;

-- Atualizando as chaves primárias das outras tabelas (Exercício)

-- Tabela Bairro (Exemplo)
select max(idbairro) + 1 from bairro; -- descobrindo o próximo id da tabela bairro (usa 'max' para descobrir o ultimo id adicionado + 1 para saber o próximo)

CREATE SEQUENCE BAIRRO_ID_SEQ MINVALUE 5; -- Criando a sequencia serial com a descoberta feita na consulta acima

ALTER TABLE BAIRRO ALTER IDBAIRRO SET DEFAULT NEXTVAL('BAIRRO_ID_SEQ'); -- Setando na tabela bairro na coluna da chave primária (pk) o padrão da sequência 
ALTER SEQUENCE BAIRRO_ID_SEQ OWNED BY BAIRRO.IDBAIRRO; -- Colocando a sequência como propriedade da tabela bairro e a coluna que irá ser sequencial (idbairro(pk))

-- Adicionando informações para teste
INSERT INTO BAIRRO (nome) VALUES ('Teste 1');
INSERT INTO BAIRRO (nome) VALUES ('Teste 2');

-- Verificando a adição na tabela
select * from bairro;

-- Tabela Cliente
SELECT MAX(IDCLIENTE) + 1 FROM CLIENTE;

CREATE SEQUENCE CLIENTE_ID_SEQ MINVALUE 18;

ALTER TABLE CLIENTE ALTER IDCLIENTE SET DEFAULT NEXTVAL('CLIENTE_ID_SEQ'); -- DEFININDO A SEQUÊNCIA CRIADA COMO DEFAULT PARA AUTO INCREMENTAR
ALTER SEQUENCE CLIENTE_ID_SEQ OWNED BY CLIENTE.IDCLIENTE; -- DEFININDO QUAIS CAMPOS SERÃO OS PROPRIETÁRIOS DESSA SEQUENCIA SERIAL CRIADA

-- Inserindo pra testar
INSERT INTO 
	CLIENTE (NOME, CPF, DATA_NASCIMENTO, GENERO, LOGRADOURO, NUMERO, IDPROFISSAO, IDNACIONALIDADE, IDBAIRRO, IDCOMPLEMENTO, IDMUNICIPIO) 
VALUES ('Luís', '12345678901', '2007-04-09', 'M', 'Rua Central', '230', 1, 1, 3, 1, 5);

-- TABELA COMPLEMENTO
SELECT MAX(IDCOMPLEMENTO) FROM COMPLEMENTO;

CREATE SEQUENCE COMPLEMENTO_ID_SEQ MINVALUE 3;

ALTER TABLE COMPLEMENTO ALTER IDCOMPLEMENTO SET DEFAULT NEXTVAL('COMPLEMENTO_ID_SEQ');
ALTER SEQUENCE COMPLEMENTO_ID_SEQ OWNED BY COMPLEMENTO.IDCOMPLEMENTO;

INSERT INTO COMPLEMENTO (NOME) VALUES ('Studio');


-- TABELA FORNECEDOR
SELECT MAX(IDFORNECEDOR) + 1 FROM FORNECEDOR;

CREATE SEQUENCE FORNECEDOR_ID_SEQ MINVALUE 4;
ALTER SEQUENCE FORNECEDOR_ID_SEQ OWNED BY FORNECEDOR.IDFORNECEDOR;

ALTER TABLE FORNECEDOR ALTER IDFORNECEDOR SET DEFAULT NEXTVAL('FORNECEDOR_ID_SEQ');

INSERT INTO FORNECEDOR (NOME) VALUES ('Terabyte Shop');

SELECT * FROM FORNECEDOR;

-- Tabela Municipio
SELECT MAX(IDMUNICIPIO) + 1 FROM MUNICIPIO;

CREATE SEQUENCE MUNICIPIO_ID_SEQ MINVALUE 10;
ALTER SEQUENCE MUNICIPIO_ID_SEQ OWNED BY MUNICIPIO.IDMUNICIPIO;

ALTER TABLE MUNICIPIO ALTER IDMUNICIPIO SET DEFAULT NEXTVAL('MUNICIPIO_ID_SEQ');

INSERT INTO MUNICIPIO (NOME, IDUF) VALUES ('Xique-Xique', 7)  

select * from municipio_uf;

-- Tabela UF
SELECT MAX(IDUF) + 1 FROM UF;

CREATE SEQUENCE UF_ID_SEQ MINVALUE 7;
ALTER SEQUENCE UF_ID_SEQ OWNED BY UF.IDUF;

ALTER TABLE UF ALTER IDUF SET DEFAULT NEXTVAL('UF_ID_SEQ');

INSERT INTO UF (NOME, SIGLA) VALUES ('Bahia', 'BA');

-- Tabela Nacionalidade
SELECT MAX(IDNACIONALIDADE) + 1 FROM NACIONALIDADE;

CREATE SEQUENCE NACIONALIDADE_ID_SEQ MINVALUE 5;
ALTER SEQUENCE NACIONALIDADE_ID_SEQ OWNED BY NACIONALIDADE.IDNACIONALIDADE; 

ALTER TABLE NACIONALIDADE ALTER IDNACIONALIDADE SET DEFAULT NEXTVAL('NACIONALIDADE_ID_SEQ');

INSERT INTO NACIONALIDADE (NOME) VALUES ('Japonesa');

-- Tabela Pedidos
SELECT MAX(IDPEDIDO) + 1 FROM PEDIDO;

CREATE SEQUENCE PEDIDO_ID_SEQ MINVALUE 16 OWNED BY PEDIDO.IDPEDIDO;
ALTER TABLE PEDIDO ALTER IDPEDIDO SET DEFAULT NEXTVAL('PEDIDO_ID_SEQ');

INSERT INTO PEDIDO (DATA_PEDIDO, VALOR, IDCLIENTE, IDVENDEDOR) VALUES (CURRENT_DATE, 130, 18, 1);

SELECT * FROM PEDIDO_INFOS

-- Pedido Produto
-- Não é necessária criar uma sequência pois a tabela referencia uma chave primária composta que são estrangeiras, logo não existe uma sequência de fato pra tabela.

-- Tabela Produto
SELECT MAX(IDPRODUTO) + 1 FROM PRODUTO;

CREATE SEQUENCE PRODUTO_ID_SEQ MINVALUE 8 OWNED BY PRODUTO.IDPRODUTO;
ALTER TABLE PRODUTO ALTER IDPRODUTO SET DEFAULT NEXTVAL('PRODUTO_ID_SEQ');

-- Tabela Profissão
SELECT MAX(IDPROFISSAO) FROM PROFISSAO;

CREATE SEQUENCE PROFISSAO_ID_SEQ MINVALUE 6 OWNED BY PROFISSAO.IDPROFISSAO;
ALTER TABLE PROFISSAO ALTER IDPROFISSAO SET DEFAULT NEXTVAL('PROFISSAO_ID_SEQ');

-- Tabela Transportadora
SELECT MAX(IDTRANSPORTADORA) + 1 FROM TRANSPORTADORA;

CREATE SEQUENCE TRANSPORTADORA_ID_SEQ MINVALUE 3 OWNED BY TRANSPORTADORA.IDTRANSPORTADORA;
ALTER TABLE TRANSPORTADORA ALTER IDTRANSPORTADORA SET DEFAULT NEXTVAL('TRANSPORTADORA_ID_SEQ');

-- Tabela Vendedor
SELECT MAX(IDVENDEDOR) + 1 FROM VENDEDOR;

CREATE SEQUENCE VENDEDOR_ID_SEQ MINVALUE 9 OWNED BY VENDEDOR.IDVENDEDOR;
ALTER TABLE VENDEDOR ALTER IDVENDEDOR SET DEFAULT NEXTVAL('VENDEDOR_ID_SEQ');