-- Campos Default

-- Default com tabela de pedido
ALTER TABLE PEDIDO ALTER COLUMN DATA_PEDIDO SET DEFAULT CURRENT_DATE; -- Caso nada for informado, a data atual é aplicada.
ALTER TABLE PEDIDO ALTER COLUMN VALOR SET DEFAULT 0; -- Caso nada for informado, o preço total do pedido é 0 (zero)

INSERT INTO PEDIDO (IDCLIENTE, IDVENDEDOR) VALUES (1, 1);
INSERT INTO PEDIDO (IDCLIENTE, IDVENDEDOR, DATA_PEDIDO, VALOR) 
VALUES (1, 1, '2022-10-10', 234);

SELECT * FROM PEDIDO;

-- APLICANDO DEFAULT NAS TABELAS (EXERCÍCIO)

-- 1. Adicione valores default na tabela de produtos do pedido
-- a. Quantidade com o valor 1
ALTER TABLE PEDIDO_PRODUTO ALTER QUANTIDADE SET DEFAULT 1; 

-- b. Valor unitário com o valor 0
ALTER TABLE PEDIDO_PRODUTO ALTER VALOR_UNITARIO SET DEFAULT 0;

INSERT INTO PEDIDO_PRODUTO (IDPEDIDO, IDPRODUTO) VALUES (1, 3);
INSERT INTO PEDIDO_PRODUTO (IDPEDIDO, IDPRODUTO, QUANTIDADE, VALOR_UNITARIO) VALUES (1, 4, 5, 100);

SELECT * FROM PEDIDO_PRODUTO;

-- 2. Adicione valor default na tabela de produtos
-- a. Valor com o valor 0
ALTER TABLE PRODUTO ALTER VALOR SET DEFAULT 0;

INSERT INTO PRODUTO (NOME, IDFORNECEDOR) VALUES ('TESTE DEFUALT 1', 1);
INSERT INTO PRODUTO (NOME, IDFORNECEDOR, VALOR) VALUES ('TESTE DEFUALT 1', 1, 50);

SELECT * FROM PRODUTO;