-- CRIANDO DATABASE BIBLIOTECA
CREATE DATABASE BIBLIOTECA;

-- \c Biblioteca -- Conecta no database pelo terminal do postgre

-- TABELA EDITORA
CREATE TABLE EDITORA (
	IDEDITORA SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,

	CONSTRAINT PK_EDT_IDEDITORA PRIMARY KEY (IDEDITORA),
	CONSTRAINT UN_EDT_NOME UNIQUE (NOME)
);

INSERT INTO EDITORA (NOME) VALUES ('Bookman');
INSERT INTO EDITORA (NOME) VALUES ('Edgard Blusher');
INSERT INTO EDITORA (NOME) VALUES ('Nova Terra');
INSERT INTO EDITORA (NOME) VALUES ('Brasport');

-- TABELA CATEGORIA
CREATE TABLE CATEGORIA (
	IDCATEGORIA SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,

	CONSTRAINT PK_CTG_IDCATEGORIA PRIMARY KEY (IDCATEGORIA),
	CONSTRAINT UN_CTG_NOME UNIQUE (NOME)
);

INSERT INTO CATEGORIA (NOME) VALUES ('Banco de Dados');
INSERT INTO CATEGORIA (NOME) VALUES ('HTML');
INSERT INTO CATEGORIA (NOME) VALUES ('Java');
INSERT INTO CATEGORIA (NOME) VALUES ('PHP');

-- TABELA AUTOR
CREATE TABLE AUTOR (
	IDAUTOR SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,

	CONSTRAINT PK_AUT_IDAUTOR PRIMARY KEY (IDAUTOR)
);

INSERT INTO AUTOR (NOME) VALUES ('Waldemar Setzer');
INSERT INTO AUTOR (NOME) VALUES ('Flávio Soares');
INSERT INTO AUTOR (NOME) VALUES ('John Watson');
INSERT INTO AUTOR (NOME) VALUES ('Rui Rossi dos Santos');
INSERT INTO AUTOR (NOME) VALUES ('Antonio Pereira de Resende');
INSERT INTO AUTOR (NOME) VALUES ('Claudiney Calixto Lima');
INSERT INTO AUTOR (NOME) VALUES ('Evandro Carlos Teruel');
INSERT INTO AUTOR (NOME) VALUES ('Ian Graham');
INSERT INTO AUTOR (NOME) VALUES ('Fabrício Xavier');
INSERT INTO AUTOR (NOME) VALUES ('Pablo Dalioglio');

-- TABELA LIVRO
-- Caso queira colocar o livro com + de uma categoria iria precisar de uma tabela LIVRO_CATEGORIA
CREATE TABLE LIVRO (
	IDLIVRO SERIAL NOT NULL,
	IDEDITORA INTEGER NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME VARCHAR(100) NOT NULL,

	CONSTRAINT PK_LVR_IDLIVRO PRIMARY KEY (IDLIVRO),
	CONSTRAINT FK_LVR_IDEDITORA FOREIGN KEY (IDEDITORA) REFERENCES EDITORA (IDEDITORA),
	CONSTRAINT FK_LVR_IDCATEGORIA FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA),
	CONSTRAINT UN_LVR_NOME UNIQUE (NOME)
);

INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (2, 1, 'Banco de Dados - 1 Edição');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (1, 1, 'Oracle DataBase 11G Administração');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (3, 3, 'Programação de Computadores Java');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (4, 3, 'Programação Orientada a Aspectos em Java');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (4, 2, 'HTML5 - Guia Prático');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (3, 2, 'XHTML: Guia de Referência para Desenvolvimento na Web');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (4, 4, 'PHP para Desenvolvimento profissonal');
INSERT INTO LIVRO (IDEDITORA, IDCATEGORIA, NOME) 
VALUES (2, 4, 'PHP com Programação Orientada a Objetos');

-- TABELA LIVRO_AUTOR
CREATE TABLE LIVRO_AUTOR (
	IDLIVRO INTEGER NOT NULL,
	IDAUTOR INTEGER NOT NULL,

	CONSTRAINT PK_LVA_IDLIVROAUTOR PRIMARY KEY (IDLIVRO, IDAUTOR)
	CONSTRAINT FK_LVA_IDLIVRO FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO);
	CONSTRAINT FK_LVA_IDAUTOR FOREIGN KEY (IDAUTOR) REFERENCES AUTOR (IDAUTOR);
);


INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (1, 1);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (1, 2);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (2, 3);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (3, 4);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (4, 5);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (4, 6);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (5, 7);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (6, 8);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (7, 9);
INSERT INTO LIVRO_AUTOR (IDLIVRO, IDAUTOR)
VALUES (8, 10);

-- Tabela ALUNO

CREATE TABLE ALUNO (
	IDALUNO SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,

	CONSTRAINT PK_ALN_IDALUNO PRIMARY KEY (IDALUNO)
);

INSERT INTO ALUNO (NOME) VALUES ('Mário');
INSERT INTO ALUNO (NOME) VALUES ('João');
INSERT INTO ALUNO (NOME) VALUES ('Paulo');
INSERT INTO ALUNO (NOME) VALUES ('Pedro');
INSERT INTO ALUNO (NOME) VALUES ('Maria');

-- Tabela Empréstimo
CREATE TABLE EMPRESTIMO (
	IDEMPRESTIMO SERIAL NOT NULL,
	IDALUNO INTEGER NOT NULL,
	DATA_EMPRESTIMO DATE NOT NULL DEFAULT CURRENT_DATE, -- Definindo Current_Date como padrão na criação da tabela.
	DATA_DEVOLUCAO DATE NOT NULL,
	VALOR DECIMAL NOT NULL DEFAULT 0,
	DEVOLVIDO CHAR(1) NOT NULL,

	CONSTRAINT PK_EMP_IDEMPRESTIMO PRIMARY KEY (IDEMPRESTIMO),
	CONSTRAINT FK_EMP_IDALUNO FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (1, '2012-05-02', '2012-05-12', 10, 'S'); 

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (1, '2012-04-23', '2012-05-03', 5, 'N'); 

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (2, '2012-05-10', '2012-05-20', 12, 'N'); 

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (3, '2012-05-10', '2012-05-20', 8, 'S'); 

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (4, '2012-05-05', '2012-05-15', 15, 'N'); 

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (4, '2012-05-07', '2012-05-17', 20, 'S');

INSERT INTO EMPRESTIMO (IDALUNO, DATA_EMPRESTIMO, DATA_DEVOLUCAO, VALOR, DEVOLVIDO)
VALUES (4, '2012-05-08', '2012-05-18', 5, 'S');

-- Tabela EMPRESTIMO_LIVRO
CREATE TABLE EMPRESTIMO_LIVRO (
	IDEMPRESTIMO INTEGER NOT NULL,
	IDLIVRO INTEGER NOT NULL,

	CONSTRAINT PK_EPL_IDEMPRESTIMOLIVRO PRIMARY KEY (IDEMPRESTIMO, IDLIVRO),
	CONSTRAINT FK_EPL_IDEMPRESTIMO FOREIGN KEY (IDEMPRESTIMO) REFERENCES EMPRESTIMO (IDEMPRESTIMO),
	CONSTRAINT FK_EPL_IDLIVRO FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
);


INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (1, 1);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (2, 4);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (2, 3);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (3, 2);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (3, 7);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (4, 5);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (5, 4);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (6, 6);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (6, 1);
INSERT INTO EMPRESTIMO_LIVRO (IDEMPRESTIMO, IDLIVRO)
VALUES (7, 8);

-- Criando index

CREATE INDEX IDX_EMP_EMPRESTIMO ON EMPRESTIMO (DATA_EMPRESTIMO);
CREATE INDEX IDX_EMP_DEVOLUCAO ON EMPRESTIMO (DATA_DEVOLUCAO);

