-- Dominios: Tipo de dado específico definido pelo usuário a fim de que todos ficam padronizados
-- Os dominios devem ser definidos com base nas tabelas em qual tão sendo criados.
-- Recomenda-se invés de criar os dominíos junto com as tabelas, para que já fiquem com o tipo criado pelo usuário, e sejam mais fácil de identificar futuramente.

-- Tipos numericos: https://www.postgresql.org/docs/current/datatype-numeric.html

-- Ids
create domain idcurto as smallint;
create domain idmedio as integer; 
create domain idlongo as bigint;
-- Caracteres
CREATE DOMAIN SIGLA AS CHAR(3);
CREATE DOMAIN CODIGO AS VARCHAR(10);
CREATE DOMAIN NOME_CURTO AS VARCHAR(15);
CREATE DOMAIN NOME_MEDIO AS VARCHAR(50);
CREATE DOMAIN NOME_LONGO AS VARCHAR(70);

-- Data e hora
CREATE DOMAIN DATA AS DATE;
CREATE DOMAIN HORA AS TIME;
CREATE DOMAIN DATA_HORA AS TIMESTAMP;

-- Numéricos
CREATE DOMAIN MOEDA AS NUMERIC(10, 2); -- Até 10 valores com 2 casas decimais
CREATE DOMAIN FLOAT_CURTO AS NUMERIC(6, 2); -- Até 6 valores com 2 casas decimais
CREATE DOMAIN FLOAT_MEDIO AS NUMERIC(10, 2); -- Até 10 valores com 2 casas decimais
CREATE DOMAIN FLOAT_LONGO AS NUMERIC(15, 2); -- Até 15 valores com 2 casas decimais

-- novos Dominios
CREATE DOMAIN CPF AS CHAR(11);
CREATE DOMAIN CHAR_FLAG AS CHAR(1); 
CREATE DOMAIN QUANTIDADE AS SMALLINT;

-- Alterando os tipos para os dominios

-- Caso a tabela escolhida tenha uma view ou esteja relacionada, não será possível trocar o tipo de dados. Por isso é tão importante criar o tipo antes de tudo.
Alter table bairro alter column nome type nome_medio; -- Alterando o tipo para o dominio criado

/*
O objetivo deste exercício é alterar os tipos de dados dos atributos de todas as tabelas, 
considerando os domínios criados anteriormente. Caso julgue necessário, faça a criação de novos domínios
*/

-- Bairro Auditoria
Alter table bairro_auditoria alter column idbairro type idcurto;
Alter table bairro_auditoria alter column data_criacao type DATA_HORA;

-- Cliente
ALTER TABLE CLIENTE ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE CLIENTE ALTER COLUMN CPF TYPE CPF;
ALTER TABLE CLIENTE ALTER COLUMN RG TYPE CODIGO;
ALTER TABLE CLIENTE ALTER COLUMN DATA_NASCIMENTO TYPE DATA;
ALTER TABLE CLIENTE ALTER COLUMN GENERO TYPE CHAR_FLAG;
ALTER TABLE CLIENTE ALTER COLUMN LOGRADOURO TYPE NOME_MEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDPROFISSAO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDNACIONALIDADE TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDBAIRRO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDCOMPLEMENTO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDMUNICIPIO TYPE IDMEDIO;

DROP VIEW CLIENTE_INFOS;
DROP VIEW CLIENTE_PROFISSAO;
DROP VIEW PEDIDO_INFOS;
DROP VIEW PRODUTO_FORNECEDOR;
DROP VIEW PEDIDO_VALORES;
DROP VIEW MUNICIPIO_UF;
DROP VIEW TRANSPORTADORA_UF;

-- Complemento
ALTER TABLE COMPLEMENTO ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Fornecedor
ALTER TABLE FORNECEDOR ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Municipio
ALTER TABLE MUNICIPIO ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE MUNICIPIO ALTER COLUMN IDUF TYPE IDMEDIO;

-- Nacionalidade
ALTER TABLE NACIONALIDADE ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Pedido
ALTER TABLE PEDIDO ALTER COLUMN IDCLIENTE TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN IDTRANSPORTADORA TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN IDVENDEDOR TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN DATA_PEDIDO TYPE DATA;
ALTER TABLE PEDIDO ALTER COLUMN VALOR TYPE MOEDA;

-- Pedido Produto
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN IDPEDIDO TYPE IDMEDIO;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN IDPRODUTO TYPE IDMEDIO;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN QUANTIDADE TYPE QUANTIDADE;-- Bairro Auditoria
Alter table bairro_auditoria alter column idbairro type idcurto;
Alter table bairro_auditoria alter column data_criacao type DATA_HORA;

-- Cliente
ALTER TABLE CLIENTE ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE CLIENTE ALTER COLUMN CPF TYPE CPF;
ALTER TABLE CLIENTE ALTER COLUMN RG TYPE CODIGO;
ALTER TABLE CLIENTE ALTER COLUMN DATA_NASCIMENTO TYPE DATA;
ALTER TABLE CLIENTE ALTER COLUMN GENERO TYPE CHAR_FLAG;
ALTER TABLE CLIENTE ALTER COLUMN LOGRADOURO TYPE NOME_MEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDPROFISSAO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDNACIONALIDADE TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDBAIRRO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDCOMPLEMENTO TYPE IDMEDIO;
ALTER TABLE CLIENTE ALTER COLUMN IDMUNICIPIO TYPE IDMEDIO;

DROP VIEW CLIENTE_INFOS;
DROP VIEW CLIENTE_PROFISSAO;
DROP VIEW PEDIDO_INFOS;
DROP VIEW PRODUTO_FORNECEDOR;
DROP VIEW PEDIDO_VALORES;
DROP VIEW MUNICIPIO_UF;
DROP VIEW TRANSPORTADORA_UF;

-- Complemento
ALTER TABLE COMPLEMENTO ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Fornecedor
ALTER TABLE FORNECEDOR ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Municipio
ALTER TABLE MUNICIPIO ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE MUNICIPIO ALTER COLUMN IDUF TYPE IDMEDIO;

-- Nacionalidade
ALTER TABLE NACIONALIDADE ALTER COLUMN NOME TYPE NOME_MEDIO;

-- Pedido
ALTER TABLE PEDIDO ALTER COLUMN IDCLIENTE TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN IDTRANSPORTADORA TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN IDVENDEDOR TYPE IDMEDIO;
ALTER TABLE PEDIDO ALTER COLUMN DATA_PEDIDO TYPE DATA;
ALTER TABLE PEDIDO ALTER COLUMN VALOR TYPE MOEDA;

-- Pedido Produto
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN IDPEDIDO TYPE IDMEDIO;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN IDPRODUTO TYPE IDMEDIO;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN QUANTIDADE TYPE QUANTIDADE;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN VALOR_UNITARIO TYPE MOEDA;

-- PEDIDOS APAGADOS
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDPEDIDO TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDCLIENTE TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDTRANSPORTADORA TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDVENDEDOR TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN DATA_PEDIDO TYPE DATA;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN VALOR TYPE MOEDA;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN DATA_REMOCAO TYPE DATA_HORA;

-- PRODUTO
ALTER TABLE PRODUTO ALTER COLUMN IDFORNECEDOR TYPE IDMEDIO;
ALTER TABLE PRODUTO ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE PRODUTO ALTER COLUMN VALOR TYPE MOEDA;

-- TRANSPORTADORA
ALTER TABLE PROFISSAO ALTER COLUMN NOME TYPE NOME_MEDIO;

-- UF
ALTER TABLE UF ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE UF ALTER COLUMN SIGLA TYPE SIGLA;

-- VENDEDORA
ALTER TABLE VENDEDOR ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE PEDIDO_PRODUTO ALTER COLUMN VALOR_UNITARIO TYPE MOEDA;

-- PEDIDOS APAGADOS
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDPEDIDO TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDCLIENTE TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDTRANSPORTADORA TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN IDVENDEDOR TYPE IDMEDIO;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN DATA_PEDIDO TYPE DATA;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN VALOR TYPE MOEDA;
ALTER TABLE PEDIDOS_APAGADOS ALTER COLUMN DATA_REMOCAO TYPE DATA_HORA;

-- PRODUTO
ALTER TABLE PRODUTO ALTER COLUMN IDFORNECEDOR TYPE IDMEDIO;
ALTER TABLE PRODUTO ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE PRODUTO ALTER COLUMN VALOR TYPE MOEDA;

-- TRANSPORTADORA
ALTER TABLE PROFISSAO ALTER COLUMN NOME TYPE NOME_MEDIO;

-- UF
ALTER TABLE UF ALTER COLUMN NOME TYPE NOME_MEDIO;
ALTER TABLE UF ALTER COLUMN SIGLA TYPE SIGLA;

-- VENDEDORA
ALTER TABLE VENDEDOR ALTER COLUMN NOME TYPE NOME_MEDIO;